version: '3.8'

services:
  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: bankcards-db
    environment:
      POSTGRES_DB: bankcards_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bankcards_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис вашего приложения
  app:
    build: .
    container_name: bankcards-app
    depends_on:
      db:
        condition: service_healthy # Ждет, пока БД будет готова принимать подключения
    ports:
      - "8070:8070"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

volumes:
  postgres-data: