#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
 # - Указать настройки подключения к базе данных.
  #- Указать порт приложения.
  #- Настроить параметры безопасности и JWT.
  #- Включить Swagger UI.

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swApi
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    with-credentials: true


server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/bankcards_db
    username: postgres
    password: admin
  jpa:
  #  database: postgresql
  #  database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  #  show-sql: true
  #  properties:
  #    hibernate:
  #      # Отключаем валидацию схемы при старте
  #      hbm2ddl.auto: none
  #      jdbc.lob.non_contextual_creation: true

  liquibase:
      change-log: classpath*:db/migration/db.changelog-master.yaml
      enabled: true
      drop-first: false  # true только для разработки, если нужно пересоздать БД
      default-schema: public


jwt:
  secret: secret

app:
  card:
    encryption-key: secret