#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
 # - Указать настройки подключения к базе данных.
  #- Указать порт приложения.
  #- Настроить параметры безопасности и JWT.
  #- Включить Swagger UI.

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swApi
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    with-credentials: true


server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bankcards
    username: postgres
    password: admin
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: secret